---
- name: install SCL repository
  yum:
    name: "centos-release-scl"
    state: present
  when: ansible_distribution == "CentOS"
    
- name: Enable repository
  rhsm_repository:
    name: "{{ haproxy_yum_redhat_repository }}"
  when: ansible_distribution == "RedHat"

- name: install dependencies
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - configuration
    - haproxy
    - haproxy-dependencies

- name: install
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_install }}"
  tags:
    - configuration
    - haproxy
    - haproxy-install
  when: ansible_distribution == "CentOS"

- name: install
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enablerepo: "{{ item.enablerepo }}"
  with_items: "{{ haproxy_install }}"
  tags:
    - configuration
    - haproxy
    - haproxy-install
  when: ansible_distribution == "RedHat"

- name: enable service
  command: "scl enable rh-haproxy{{ haproxy_version | replace('.', '') }} bash"
