# handlers file for haproxy
---
- name: restart haproxy
  service:
    name: "{{ haproxy_service_name }}"
    state: "{{ haproxy_restart_handler_state }}"
  when: service_default_state | default('started') == 'started'
